In [2]:
import numpy as np

In [4]:
# Eigenvectors - Note, the eigenvectors are the columns of the output.
M = np.array([[3/2,-1],
              [-1/2,1/2]])

vals, vecs = np.linalg.eig(M)
print(vecs)
1-5**(1/2)


[[ 0.9390708   0.59069049]
 [-0.34372377  0.80689822]]


-1.2360679774997898

In [5]:
np.sqrt(3)

1.7320508075688772

In [7]:
M@np.array([1-np.sqrt(3),1])

array([-2.09807621,  0.8660254 ])

In [8]:
[1-np.sqrt(3),1]

[-0.7320508075688772, 1]

In [9]:
M@M

array([[ 2.75, -2.  ],
       [-1.  ,  0.75]])

In [10]:
c= np.array([[-1-np.sqrt(3),-1+np.sqrt(3)],
              [1,1]])
c 

array([[-2.73205081,  0.73205081],
       [ 1.        ,  1.        ]])

In [17]:
c.T@M@c

array([[15.79422863, -0.1339746 ],
       [-1.8660254 ,  0.20577137]])