# Basic Numpy

In [70]:
import numpy as np

## 기본 자료구조 (Numpy array)

In [72]:
# 복합 자료형 list는 변환할 수 없음
# 해당 자료형을 전부 포괄 할 수 있는 자료형이 있다면 해당 자료형으로 converting 후 변환
week = np.array([0, 'mon', 1.0, 2, 3, 'fri', 'sat', 6.0])
print(week, type(week), week.dtype)

['0' 'mon' '1.0' '2' '3' 'fri' 'sat' '6.0'] <class 'numpy.ndarray'> <U11


In [74]:
# 사이즈가 같은 중첩된 list는 같은 규칙에 의해 numpy array로 전환됨 
people = np.array([['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57]])
print(people, type(people), people.shape)

<class 'numpy.ndarray'> (3, 3)


In [76]:
# 사이즈가 다른 중첩된 list는 numpy array로 변환 될 수 없음
# 혀용되는 numpy array에 각 원소를 다시 list를 갖는 numpy array로 변환
people = np.array([['son', 176, 69], ['kim', 183, 84], ['lee', 163, 57], ['bug!', 183, 123, 341]])
print(people, type(people), people.shape, people.dtype)

[list(['son', 176, 69]) list(['kim', 183, 84]) list(['lee', 163, 57])
 list(['bug!', 183, 123, 341])] <class 'numpy.ndarray'> (4,) object


## np array 구조 (shape, ndim, axis, len, size)

In [79]:
#1차원 array 선언
a1 = np.array([7,2,9,10])

#len, shape, ndim 출력
print('len', len(a1))
print('shape', a1.shape)
print('ndim', a1.ndim)
print('size', a1.size)

len 4
shape (4,)
ndim 1
size 4


In [80]:
#2차원 array 선언
a2 = np.array([[5.2, 3.0, 4.5],
               [9.1, 0.1, 0.3]])

#len, shape, ndim 출력
print('len', len(a2))
print('shape', a2.shape)
print('ndim', a2.ndim)
print('size', a2.size)

len 2
shape (2, 3)
ndim 2
size 6


In [81]:
#3차원 array 선언
a3 = np.array([
    [[1, 2], [4, 3], [7, 4]],
    [[2, 1], [9, 2], [7, 5]],
    [[1, 8], [3, 4], [0, 2]],
    [[9, 4], [6, 2], [9, 8]]])

#len, shape, ndim 출력
print('len', len(a3))
print('shape', a3.shape)
print('ndim', a3.ndim)
print('size', a3.size)

len 4
shape (4, 3, 2)
ndim 3
size 24


## np array 기본 함수

In [82]:
a = np.array([1, 2, 3, 4, 5])
#a를 전체 item 기준으로 sum과 prod 계산
print(np.sum(a)) # 15 = 1+2+3+4+5
print(np.prod(a)) # 120 = 1*2*3*4*5

15
120


In [88]:
#a를 전체 item 기준으로 평균, 분산, 표준편차 계산
print(np.mean(a)) # 3.0 = (1+2+3+4+5)/5
print(np.var(a)) # 2.0: variance
print(np.std(a)) # 1.414..: std


5.5
8.25
2.8722813232690143


In [89]:
#a를 전체 item 기준으로 최소, 최대값 계산
print(np.min(a)) # 1: minimum
print(np.max(a)) # 5: maximum

1
10


In [90]:
#a를 전체 item 기준으로 최소, 최대값의 index위치를 반환
print(np.argmin(a)) # 0: the index of the min. value
print(np.argmax(a)) # 4: the index of the max. value

0
9


In [92]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#axis를 바꿔가며 sum, prod 계산
print(np.sum(a), np.sum(a, axis=0), np.sum(a, axis=1))
print(np.prod(a), np.prod(a, axis=0), np.prod(a, axis=1))

55 [ 7  9 11 13 15] [15 40]
3628800 [ 6 14 24 36 50] [  120 30240]


In [93]:
#axis를 바꿔가며 mean, var, std 계산
print(np.mean(a), np.mean(a, axis=0), np.mean(a, axis=1))
print(np.var(a), np.var(a, axis=0), np.var(a, axis=1))
print(np.std(a), np.std(a, axis=0), np.std(a, axis=1))

5.5 [3.5 4.5 5.5 6.5 7.5] [3. 8.]
8.25 [6.25 6.25 6.25 6.25 6.25] [2. 2.]
2.8722813232690143 [2.5 2.5 2.5 2.5 2.5] [1.41421356 1.41421356]


In [94]:
#axis를 바꿔가며 min, max 계산
print(np.min(a), np.min(a, axis=0), np.min(a, axis=1))
print(np.max(a), np.max(a, axis=0), np.max(a, axis=1))

1 [1 2 3 4 5] [1 6]
10 [ 6  7  8  9 10] [ 5 10]


In [95]:
#axis를 바꿔가며 argmin, argmax 계산
print(np.argmin(a), np.argmin(a, axis=0), np.argmin(a, axis=1))
print(np.argmax(a), np.argmax(a, axis=0), np.argmax(a, axis=1))

0 [0 0 0 0 0] [0 0]
9 [1 1 1 1 1] [4 4]


## indexing & slicing

In [97]:
data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#각 원소를 index를 이용하여 출력
print(data[0], data[1])
print(data[0][1], data[1][2])
print(data[0, 1], data[1 ,2])

[1 2 3 4 5] [ 6  7  8  9 10]
2 8
2 8


In [42]:
#연속된 원소를 slice를 이용하여 출력
print(data[0:1])
print(data[0:2])

print(data[0:1, 3])
print(data[0:2, 3])

[[1 2 3 4 5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[4]
[4 9]


## np 산술 연산

In [99]:
a = np.array([[1,2],
              [3,4]])

b = np.array([[2,1],
              [4,3]])

In [100]:
# element-wise product 연산
print(a * b)

[[ 2  2]
 [12 12]]


In [101]:
# matrix-multiplication 연산
print(a @ b)
print(np.matmul(a, b))
print(np.dot(a, b))

[[10  7]
 [22 15]]
[[10  7]
 [22 15]]
[[10  7]
 [22 15]]


## Transpose

In [104]:
# 2차원 np array 선언
a = np.array([[1,2,3,4]])
print(a.T, a.T.shape)

b = np.array([1,2,3,4])
print(b.T, b.T.shape)

[[1]
 [2]
 [3]
 [4]] (4, 1)
[1 2 3 4] (4,)
